### ISSUE TITLE
Run shortcodes in description and title

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1867]
Currently we have "run shortcodes in autogenerated descriptions" but we should discuss running them (optionally?) in user-created titles and descriptions.

We need to discuss:

1) whether to do this 
2) any negative effects (plugin conflicts?) https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues?q=is%3Aissue+shortcode+is%3Aclosed

**Comment by arnaudbroes** [comment]
Duplicate of #1846.

**Comment by michaeltorbert** [comment]
@arnaudbroes This isn't a duplicate. That's a reference to an existing option "Run Shortcodes in Autogenerated Descriptions". This is for new functionality.

**Comment by arnaudbroes** [comment]
@michaeltorbert my bad, acted a bit too fast.

**Comment by Garconis** [comment]
Shortcodes currently work in the Social Meta addon via: https://d.pr/free/i/3t1Hkb

So I don't understand why you wouldn't already have an option to also allow it to work for the regular Title and Description area as well: https://d.pr/free/i/p97okj

**Comment by itinchev** [comment]
We are also running a project in which a shortcode needs to be applied/executed in the title and description with SEO purposes. Can you please suggest a way this feature to be added to the current version (in functions.php of the theme or external plugin) if you are not planning to include it officially soon? Thanks.

**Comment by Pikamander2** [comment]
I'm also in need of this.

**Comment by Garconis** [comment]
Hoping for this functionality soon. I'm in need of this, for another project. Where I'd like to add a shortcode to both the SEO Title and the SEO Description, which would then output the desired text (based on the logic of my own shortcode) [which uses conditional if statements based on page slug,  parent/child page, etc.]

**Comment by denra-dot-com** [comment]
Hello,
Yes, it is a plugin we've created for the purpose. We were searching for it and finally made it ourselves. Now we've shared it for everyone to use it.

**Comment by Pikamander2** [comment]
@denra-dot-com - Thanks for the plugin! Have you made a pull request by chance? It would be fantastic if this code were built-in to the All In One SEO Pack.

**Comment by denra-dot-com** [comment]
No, we are using the WordPress repository only and have not made a pull request here. I've written with the username itinchev above but now I made the username we are currently using for our projects - denra(-dot-com). The plugin works great with common shortcodes and and ones where the attributes are not split by space i.e. [shortcode] and [shortcode attr1="something-1" attr2="something-2"] will work just fine but [shortcode attr1="something 1" attr2="something 2"] (see the spaces in the attributes) will not produce a correct result, which is due to removed double quotes double processing of the code somewhere in the source of All in One SEO Pack. So it is not a perfect solution but it good enough to be used in the 99% of the cases and help us do the job.

**Comment by Pikamander2** [comment]
@denra-dot-com - It looks like your plugin doesn't affect the AIOSP schema at all, so the raw shortcodes appear in the `.aioseop-schema` element. Can you confirm whether that's the case?

**Comment by denra-dot-com** [comment]
@Pikamander2 we did not make it work on the schema but on SEO title, description and keywords for now. This was what we needed. (Plus a few other locations listed in the settings). I have to check how it works with the `.aioseop-schema` and will publish update soon when/if it is supported.

**Comment by denra-dot-com** [comment]
FYI: Schema support was added in the latest version of Do Shortcodes for All in One SEO Pack which was released today.

**Comment by wpsmort** [comment]
Moving this to our new feature request system.

**Comment by Pikamander2** [comment]
@denra-dot-com - One of the AIOSEO updates released in January appears to have broken support for shortcodes in the titles.

@wpsmort - Any updates on native support for this? We would prefer not to have to rely on a third party plugin.

**Comment by Pikamander2** [comment]
Adding these lines to our child theme's functions.php file appears to work for most purposes:

```
add_filter('the_title', 'do_shortcode');
add_filter('single_post_title', 'do_shortcode');
add_filter('aioseo_title', 'do_shortcode');
add_filter('aioseo_description', 'do_shortcode');
```

However, the AIOSEO schema still shows the raw shortcode:

```
<script type="application/ld+json" class="aioseo-schema">
...,"name":"Product #3682: $[current_price]","...
</script>
```

Is there an existing filter that can be used to fix the above issue, or does a new one need to be added?

**Comment by Pikamander2** [comment]
The offending line in the plugin's source code appears to be line 138:

```
case '%postname%':
	$breadcrumb = [
		'name'        => $post->post_title,
		'description' => aioseo()->meta->description->getDescription( $post ),
		'url'         => $url[0],
		'type'        => $this->getPostGraph()
	];
	break;
```

The `$post->post_title` line doesn't seem to get filtered in any way

Interestingly, looking through the rest of that file, the post title related code seems to be pretty inconsistent in general. Several functions use `$post->post_title` while others use `aioseo()->meta->title->getTitle( $post )`.

The latter seems to fix the breadcrumb schema shortcode issue mentioned above, so it would be nice if we could modify the plugin's code to look like this:

```
case '%postname%':
	$breadcrumb = [
		'name'        => aioseo()->meta->title->getTitle( $post ),
		'description' => aioseo()->meta->description->getDescription( $post ),
		'url'         => $url[0],
		'type'        => $this->getPostGraph()
	];
	break;
```

I'll submit a pull request.

**Comment by arnaudbroes** [comment]
@Pikamander2 that isn't something we're going to do because we're trying to move away from `getTitle()` for our schema since that returns the SEO title, and for Breadcrumb, we simply want the plain post title.

What I'm thinking of is simply running shortcodes on the JSON before we output it. Would that work for you? You can test it by going to Common\Schema\Schema.php and replacing `return wp_json_encode( $schema );` on line 96 (give or take depending on the version you're on) with `return aioseo()->helpers->doShortcodes( wp_json_encode( $schema ) );`

**Comment by Pikamander2** [comment]
Ideally, it would be nice to be able to filter the title before it gets converted into JSON. That seems like a more standard and developer-friendly approach since you would then only have to do something like this:

    add_filter('the_title', 'do_shortcode');

Rather than having to create a separate function for parsing the JSON, which could prove to be problematic if the JSON's structure changes in the future.

**Comment by denra-dot-com** [comment]
Hello,
The "Do Shortcodes for All in One SEO Pack" plugin does not work with the new version of AIOSEO. I started making a new version but the the support of AIOSEO team claims that shortcodes are supported in the new version. (I will be more than happy if this is true but I do not see it working that way for now.)

You may join the Support threat on WordPress.org and also help clarifay the issues:
https://wordpress.org/support/topic/list-of-aioseo-hooks/

**Comment by arnaudbroes** [comment]
We added support for this a while ago in https://github.com/awesomemotive/aioseo/issues/1163

**Comment by Garconis** [comment]
Page not found.

**Comment by Garconis** [comment]
> We added support for this a while ago in [awesomemotive/aioseo#1163](https://github.com/awesomemotive/aioseo/issues/1163)

Page not found

**Comment by arnaudbroes** [comment]
@Garconis that's just for us internally.

It was fixed in 4.0.13 - https://aioseo.com/changelog/

**Comment by JohhnyCashh** [comment]
> @Garconis that's just for us internally.
> 
> It was added in 4.0.13 - https://aioseo.com/changelog/

I tried to use new filter but it doesn't work in schema for some reason.
I added this line in functions.php 
`add_filter('aioseo_schema_graphs','do_shortcode');`

But after that in one place of schema still shows the raw shortcode
```
<script type="application/ld+json" class="aioseo-schema">
...,"name":"Test H1 [month_year]","...
</script>
```

What did I do wrong? Maybe I should add a new function?

**Comment by arnaudbroes** [comment]
@JohhnyCashh that does not work because the filter you're using is used to control the graphs that are output on the page (e.g. Article, WebSite, Organization, Person, Product, etc.). It does not pass the output of those graphs. We still need to add a filter for this.
